### ISSUE TITLE
Доработка пункта "До нас легко добраться"

### ISSUE THREAD

**Issue by farakhov-marsel** [mrf-s/MrfServiceFrontend#14]
Убери почту пожалуйста
г. Казань, ул. Чапаева, Авиастроительный район, дом 16, подъезд 1, этаж 3, квартира 10 [Перед Вашим приходом, просьба позвонить]
Ежедневно с 10:00 до 00:00, без выходных

**Comment by farakhov-marsel** [comment]
Я по почте никогда не буду связываться с клиентами, терпеть не могу эти все хуйни, любая связь с клиентом исключительно через WhatsApp и ТГ

**Comment by farakhov-marsel** [comment]
г. Казань, ул. Чапаева, Авиастроительный район, дом 16, подъезд 1, этаж 3, квартира 10 (Перед Вашим приходом, просьба позвонить)

**Comment by NotIlya4** [comment]
Контактный телефон (WhatsApp)

**Comment by farakhov-marsel** [comment]
Контактный телефон [WhatsApp]

**Comment by farakhov-marsel** [comment]
![Image](https://github.com/mrf-s/MrfServiceFrontend/assets/135541271/2029ffdf-6049-4cc9-9f24-5c03ff524e54)

**Comment by farakhov-marsel** [comment]
![Image](https://github.com/mrf-s/MrfServiceFrontend/assets/135541271/297c05ff-f859-4333-b50c-0a248f321951)

**Comment by farakhov-marsel** [comment]
https://vk.com/mr.farakhov

**Comment by farakhov-marsel** [comment]
MR.Farakhov
